server:
  port: 9001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/ship?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  #Freemarker
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    servlet:
      content-type: text/html

ship:
  user-password-salt: d5ec0a02

nacos:
  discovery:
    server-addr: 127.0.0.1:8848

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml

